args:
  _examples: |
    rdppass
    wrdp --location officeda --pass-env
    wrdp --location home --pass-env --low-res
    wrdp --location home --pass-env --monitors 1 2
    wrdp --location home
    wrdp --location home
    wrdp --location home --monitor 2 --taskbar --pass-env
    wrdp --location home --monitor 2 --taskbar --pass-env --audio
    wrdp --location test --pass-env --to-cmd --window -w 960 -h 1032 -x 2326  -y 0 -d
  conf:
  _xor: monitor,monitors,window
  location:
    _label: LOCATION_NAME
    _values: '*'
    _required: true
  audio:
    _info: set audio on client

  low_res:
    _info: low resolution settings "/rfx /gfx:avc444"

  monitor:
    _info: monitor index as defined with --set-monitors
    _type: int

    decorations:
      _aliases: --decorations,-d
      _label: GAP
      _type: int
      _values: "?"

    taskbar:
      _info: keep taskbar visible

  monitors:
    _info: provide any monitor index, 1st monitor is the main one.
    _type: int
    _values: +

  pass_env:
    to_cmd:
      _info: password is added to xfreerdp cmd so it is visible with ps
      show:
  pass_fifo:
    _label: PATH
  scale:
    _info: apply parameters /scale:140 /scale-desktop:160 for tablet

  set_monitors:
    _allow_siblings: true

  window:
    decorations:
      _aliases: --decorations,-d
    x:
      _type: int
    y:
      _type: int
    width:
      _aliases: --width,-w
      _type: int
    height:
      _aliases: --height,-h
      _type: int
